version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    environment:
      - "discovery.type=single-node"
    volumes:
      - osmeshd:/usr/share/elasticsearch/data
    ports:
      - 9831:9200
volumes:
  osmeshd: {}