MQTTServer:
  server: tcp://test.carriot.ir:1883
  username: carriot
  password: Dalton@Gang
  topic: fleet/#

monitor:
  port: 2112
  url: /metrics

database:
  host: localhost
  port: 5432
  user: carriot
  password: Mypass
  db: localbackup
  connMaxLifetime: 0
  maxIdleConns: 10
  maxOpenConns: 10

#database:
#  host: 79.175.151.34
#  port: 5432
#  user: carriot
#  password: Jvk[@LpskKhl[,
#  db: carriotdb
#  connMaxLifetime: 0
#  maxIdleConns: 10
#  maxOpenConns: 10

logger:
  path: ./log.log