monitor:
  port: 2112
  url: /metrics

system:
  url : 'http://localhost/nominatim'
  threads: 5
  dataPerRequest : 600
  lng : 'fa'

elastic:
  host: localhost
  port: 9090
  password:
  topic: carriot_geo

logger:
  path: ./log.log

database:
  host: localhost
  port: 5432
  user: postgres
  password: 1234
  db: newmapsearch
  connMaxLifetime: 0
  maxIdleConns: 10
  maxOpenConns: 10
