monitor:
  port: 2112
  url: /metrics

system:
  url : 'http://localhost/nominatim'
  threads: 6
  dataPerRequest : 650
  lng : 'fa'

elastic:
  host: localhost
  port: 9831
  password:
  topic: carriot_simple_geo

logger:
  path: ./log.log

database:
  host: localhost
  port: 5432
  user: postgres
  password: 1234
  db: newmapsearch
  connMaxLifetime: 0
  maxIdleConns: 10
  maxOpenConns: 10
